In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Lecture 9 ##

## Functions ##

In [ ]:
# practice writing the spread function from the slide

# here

# passed in an array (data type)

In [2]:
def triple(x):
    return 3 * x

In [3]:
triple(3) # we passed in an integer, my input was an integer


9

In [5]:
num = 4

In [6]:
triple(num) # our input here was a variable, with a value equal to an integer

12

In [8]:
triple('num') # string

'numnumnum'

In [15]:
'hello'*3

'hellohellohello'

In [14]:
'hi' + 3.1

TypeError: can only concatenate str (not "float") to str

In [17]:
triple(num * 5) # pass in an expression, python knows to execute the expression, the value is passed in
# triple(4*5)
# triple(20)

60

In [22]:
pi = 3.14
pi

3.14

In [25]:
triple(np.pi)


9.42477796076938

In [27]:
triple(True) # boolean value

3

In [29]:
True * 3

3

In [30]:
1 * 3

3

In [28]:
triple(False)

0

In [31]:
False * 3

0

In [32]:
0 * 3

0

### Note About Scopes

In [37]:
x

NameError: name 'x' is not defined

In [46]:
x = 5
x

5

In [47]:
x = triple(2 * x)
x

30

In [42]:
x * 2

10

In [43]:
x

5

### Type Agnostic

In [48]:
triple('ha')

'hahaha'

In [49]:
triple(np.arange(4))

array([0, 3, 6, 9])

### Discussion Question

In [33]:
def percent_of_total(s):
    return np.round(s / sum(s) * 100, 2)

In [36]:
help(np.round)

Help on function round_ in module numpy:

round_(a, decimals=0, out=None)
    Round an array to the given number of decimals.
    
    See Also
    --------
    around : equivalent function; see for details.



In [34]:
percent_of_total(make_array(1,2,3,4))
# the number 10 below means, the first element which equals 1, makes up 10% of the total sum of the array

# total sum of my array above is 10
# 1/10 = 0.1 * 100 = 10%

array([10., 20., 30., 40.])

In [35]:
percent_of_total(make_array(1, 213, 38))
# what does 0.4 mean?
# sentence here: first element, which equals 1, makes up 0.4% of the total sum of the array

array([ 0.4 , 84.52, 15.08])

### Multiple Arguments

$ h^2 = x^2 + y^2 \hspace{20 pt} => \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $

In [50]:
def hypotenuse(x,y):
    hypot_squared = (x ** 2 + y ** 2)
    return hypot_squared ** 0.5

In [51]:
hypotenuse(9, 12)

15.0

In [54]:
np.sqrt(9**2 + 12**2)

15.0

In [55]:
(9**2 + 12**2) ** 0.5

15.0

In [52]:
hypotenuse(2, 2)

2.8284271247461903

## Apply ##

In [65]:
ages = Table().with_columns(
    'Person', make_array('Jim', 'Pam', 'Michael', 'Creed'),
    'Birth Year', make_array(1985, 1988, 1967, 1904)
)
ages

Person  | Birth Year
Jim     | 1985
Pam     | 1988
Michael | 1967
Creed   | 1904

In [58]:
def cap_at_1980(x):
    return min(x, 1980)

In [59]:
cap_at_1980(1975)

1975

In [60]:
cap_at_1980(1991)

1980

In [61]:
ages.apply(cap_at_1980, 'Birth Year')

# add this array to the table
# using ages.with_column(...)

array([1980, 1980, 1967, 1904])

In [63]:
def name_and_age(name, year):
    age = 2022 - year
    return name + ' is ' + str(age)

In [64]:
ages.apply(name_and_age, 'Person', 'Birth Year')

array(['Jim is 37', 'Pam is 34', 'Michael is 55', 'Creed is 118'],
      dtype='<U13')