In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Comparison ##

In [2]:
3 > 1

True

In [3]:
type(3 > 1)

bool

In [4]:
True

True

In [5]:
true

NameError: name 'true' is not defined

In [19]:
3 == 3

True

In [ ]:
# = assigning a value to a variable
# == checking for equality

In [18]:
3 = 3.0

SyntaxError: can't assign to literal (<ipython-input-18-95c681db2ea2>, line 1)

In [8]:
10 != 2

True

In [9]:
x = 14
y = 3

In [10]:
x > 15

False

In [11]:
12 < x

True

In [12]:
x < 20

True

In [13]:
12 < x < 20

True

In [14]:
10 < x-y < 13

True

In [16]:
x > 13 and y < 3.14159

False

In [17]:
x < 13 or y < 3.14159

True

## Comparisons with arrays

In [20]:
pets = make_array('cat', 'cat', 'dog', 'cat', 'dog', 'rabbit')

In [21]:
pets == 'cat'

array([ True,  True, False,  True, False, False])

In [22]:
1 + 1 + 0 + 1 + 0 + 0

3

In [27]:
sum(([ True,  True, False,  True, False, False]))

3

In [24]:
sum(pets == 'cat')

3

In [23]:
sum(make_array(True, True, False, True, False, False))

3

In [31]:
pets == 'dog'

array([False, False,  True, False,  True, False])

In [ ]:
[0,0,1,0,1,0]

In [32]:
sum([0,0,1,0,1,0])

2

In [29]:
np.count_nonzero(pets == 'dog')
# what is np.count_nonzero doing here?
# what does the value 2 mean below?
# displaying the number of True values in our expression pets == 'dog'
# how many times does dog appear in my pets array?
# twice

2

In [33]:
help(np.count_nonzero)

Help on function count_nonzero in module numpy:

count_nonzero(a, axis=None)
    Counts the number of non-zero values in the array ``a``.
    
    The word "non-zero" is in reference to the Python 2.x
    built-in method ``__nonzero__()`` (renamed ``__bool__()``
    in Python 3.x) of Python objects that tests an object's
    "truthfulness". For example, any number is considered
    truthful if it is nonzero, whereas any string is considered
    truthful if it is not the empty string. Thus, this function
    (recursively) counts how many elements in ``a`` (and in
    sub-arrays thereof) have their ``__nonzero__()`` or ``__bool__()``
    method evaluated to ``True``.
    
    Parameters
    ----------
    a : array_like
        The array for which to count non-zeros.
    axis : int or tuple, optional
        Axis or tuple of axes along which to count non-zeros.
        Default is None, meaning that non-zeros will be counted
        along a flattened version of ``a``.
    
        .. vers

In [35]:
x = np.arange(20, 31)
x

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [37]:
sum(x > 28)

2

## Simulation

Let's play a game: we each roll a die. 

If my number is bigger: you pay me a dollar.

If they're the same: we do nothing.

If your number is bigger: I pay you a dollar.

Steps:
1. Find a way to simulate two dice rolls.
2. Compute how much money we win/lose based on the result.
3. Do steps 1 and 2 10,000 times.

### Conditional Statements

In [38]:
# Work in progress
def one_round(my_roll, your_roll):
    if my_roll > your_roll:
        return 1

In [39]:
one_round(4, 3)
# you owe me $1

1

In [40]:
one_round(2, 6)
# why isn't there anything printed to the screen when you roll a number bigger than mine?



In [54]:
# Final correct version
def one_round(my_roll, your_roll):
    if my_roll > your_roll:
        return 1
    elif your_roll > my_roll: # elif stands for else if:
        return -1
    elif your_roll == my_roll:
        return 0

In [42]:
one_round(1, 1)

0

In [43]:
one_round(6, 5)

1

In [44]:
one_round(7, -1)
# try again, use a number found on a six-sided die

1

In [ ]:
# goal: rewrite function one_round to
# make sure we enter in numbers that are found on a six-sided die
# BONUS: check for data type of input, do not accept decimals
# come back at 11:46

# make sure my_roll, your_roll are integers
# make sure they're between or equal to 1 and 6 OR between 0 and 7


In [50]:
# Checking for real numbers on a six-sided die

def one_round(my_roll, your_roll):
    # make sure my_roll, your_roll are integers
    if type(my_roll) == int and type(your_roll == int):
        # make sure they're between or equal to 1 and 6 OR between 0 and 7
        if 0 < my_roll < 7 and 0 < your_roll < 7:
            if my_roll > your_roll:
                return 1
            elif your_roll > my_roll: # elif stands for else if:
                return -1 
            elif your_roll == my_roll:
                return 0
        else: 
            print("try again, use a number found on a six-sided die")
    else: 
        print("try again, use a number found on a six-sided die")

        
        
    

In [51]:
one_round(7, -1)


try again, use a number found on a six-sided die


### Random Selection

In [55]:
mornings = make_array('wake up', 'sleep in')

In [63]:
np.random.choice(mornings)

'wake up'

In [57]:
np.random.choice(mornings)

'sleep in'

In [58]:
np.random.choice(mornings)

'sleep in'

In [64]:
np.random.choice(mornings, 7)

array(['sleep in', 'wake up', 'wake up', 'sleep in', 'sleep in',
       'wake up', 'wake up'], dtype='<U8')

In [66]:
np.random.choice(mornings, 7) == 'wake up'
# 'wake up ' appears four times in my random selection of the mornings array
# i should wake up 4 times this week, right when my alarm goes off


array([False, False,  True,  True,  True,  True, False])

In [67]:
sum(np.random.choice(mornings, 7) == 'sleep in')

5

In [68]:
morning_week = np.random.choice(mornings, 7)
morning_week

array(['sleep in', 'sleep in', 'sleep in', 'sleep in', 'sleep in',
       'sleep in', 'sleep in'], dtype='<U8')

In [69]:
sum(morning_week == 'wake up')

0

In [70]:
sum(morning_week == 'sleep in')

7

In [72]:
die_faces = np.arange(1, 7)
die_faces

array([1, 2, 3, 4, 5, 6])

In [73]:
np.random.choice(die_faces)

1

In [84]:
def simulate_one_round():
    my_roll = np.random.choice(die_faces)
    print('my roll is:',my_roll)
    your_roll = np.random.choice(die_faces)
    print('your roll is:',your_roll)
    return ('what is owed: $', one_round(my_roll, your_roll))

In [85]:
simulate_one_round()
# what does the value below mean?


my roll is: 1
your roll is: 2


('what is owed: $', -1)

### Appending Arrays

In [87]:
first = np.arange(4)
second = np.arange(10, 17)
print(first)
print(second)

[0 1 2 3]
[10 11 12 13 14 15 16]


In [88]:
np.append(first, 6)

array([0, 1, 2, 3, 6])

In [89]:
first

array([0, 1, 2, 3])

In [90]:
np.append(first, second)

array([ 0,  1,  2,  3, 10, 11, 12, 13, 14, 15, 16])

In [91]:
first

array([0, 1, 2, 3])

In [92]:
second

array([10, 11, 12, 13, 14, 15, 16])

### Repeated Betting ###

In [ ]:
results = make_array()

In [ ]:
results = np.append(results, simulate_one_round())
results

## `For` Statements

In [94]:
for pet in make_array('cat', 'dog', 'rabbit'):
    print('I love my ' + pet)

I love my cat
I love my dog
I love my rabbit


In [93]:
pet = make_array('cat', 'dog', 'rabbit').item(0)
print('I love my ' + pet)

pet = make_array('cat', 'dog', 'rabbit').item(1)
print('I love my ' + pet)

pet = make_array('cat', 'dog', 'rabbit').item(2)
print('I love my ' + pet)

I love my cat
I love my dog
I love my rabbit


In [ ]:
game_outcomes = make_array()

for i in np.arange(5):
    game_outcomes = np.append(game_outcomes, simulate_one_round())
    
game_outcomes

In [ ]:
game_outcomes = make_array()

for i in np.arange(10000):
    game_outcomes = np.append(game_outcomes, simulate_one_round())
    
game_outcomes

In [ ]:
len(game_outcomes)

In [ ]:
results = Table().with_column('My winnings', game_outcomes)

In [ ]:
results

In [ ]:
results.group('My winnings').barh('My winnings')

In [ ]:
# Bonus question: This simulation is relatively simple. 
# Can you find a way to run it without using a for loop?

### Another example: simulating heads in 100 coin tosses

In [ ]:
coin = make_array('heads', 'tails')

In [ ]:
sum(np.random.choice(coin, 100) == 'heads')

In [ ]:
# Simulate one outcome

def num_heads():
    return sum(np.random.choice(coin, 100) == 'heads')

In [ ]:
# Decide how many times you want to repeat the experiment

repetitions = 10000

In [ ]:
# Simulate that many outcomes

outcomes = make_array()

for i in np.arange(repetitions):
    outcomes = np.append(outcomes, num_heads())

In [ ]:
heads = Table().with_column('Heads', outcomes)
heads.hist(bins = np.arange(29.5, 70.6))

## Optional: Advanced `where` ##

In [ ]:
ages = make_array(16, 22, 18, 15, 19, 15, 16, 21)
age = Table().with_column('Age', ages)

In [ ]:
age

In [ ]:
age.where('Age', are.above_or_equal_to(18))

In [ ]:
voter = ages >= 18

In [ ]:
voter

In [ ]:
age.where(voter)

In [ ]:
is_voter = are.above_or_equal_to(18)

In [ ]:
type(is_voter)

In [ ]:
is_voter(22)

In [ ]:
is_voter(3)

In [ ]:
age.apply(is_voter, 'Age')

In [ ]:
ages >= 18

In [ ]:
voter

In [ ]:
def my_voter_function(x):
    return x >= 18

In [ ]:
age.where('Age', are.above_or_equal_to(18))

In [ ]:
age.where(voter)

In [ ]:
age.where('Age', my_voter_function)